### ISSUE TITLE
Add package to paletteer for discovery

### ISSUE THREAD

**Issue by davidski** [jakelawlor/PNWColors#1]
Thanks for the Cascadia-themed package! ⛰ 😄 

Please consider submitting a PR to the [paletteer](https://github.com/EmilHvitfeldt/paletteer) package so that these schemes are discoverable by users of that package. (I have no involvement in paletter, just like the catalog of palettes it gives).

Thanks again!

**Comment by jakelawlor** [comment]
Hi there, 

Thanks for the suggestion! I was not aware of the Palatteer package, but that sounds like a great idea. I will definitely do that when I have some time. 

Jake

**Comment by EmilHvitfeldt** [comment]
Hallo @jakelawlor!

I was informed about your package in https://github.com/EmilHvitfeldt/paletteer/issues/74 and have successfully merged it in. Once I get around to it, it will also appear on https://github.com/EmilHvitfeldt/r-color-palettes.

**Comment by jakelawlor** [comment]
Great, thanks @EmilHvitfeldt ! 

(and thanks for compiling Palatteer- what a great resource!) 

-J.
